local test = require('src.lua.test.common.luaunit')
require('src.lua.test.client.Utils.TDLZ_TEST_NumSet')
require('src.lua.test.client.Utils.TDLZ_TEST_Set')
require('src.lua.test.client.Utils.TDLZ_TEST_StringUtils')
os.exit(test.LuaUnit.run())